import React, { useState, useEffect } from "react";
import "./ProviderDashboard.css";

const BASE = "http://localhost:9090";
const hdrs = () => { const t=localStorage.getItem("token"); return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}; };
const fmt = n => `₹${Number(n||0).toLocaleString("en-IN")}`;

const STATUS_STYLE = {
  PAID:    { background:"#ecfdf5", color:"#059669", border:"1px solid #a7f3d0" },
  PENDING: { background:"#fffbeb", color:"#b45309", border:"1px solid #fcd34d" },
  CANCELLED:{ background:"#fef2f2",color:"#dc2626", border:"1px solid #fecaca" },
};

export default function ProviderInvoices() {
  const [invoices, setInv] = useState([]);
  const [loading, setLoad] = useState(true);
  const [error, setError]  = useState("");
  const [filter, setFilter]= useState("ALL");

  useEffect(() => { fetchInvoices(); }, []);

  async function fetchInvoices() {
    setLoad(true); setError("");
    // Admin endpoint — if provider-specific endpoint exists, use that instead
    // For now we load all and show a note; replace with /invoices/get/provider/{id} if available
    try {
      const r = await fetch(`${BASE}/invoices/getall`, { headers: hdrs() });
      if (!r.ok) throw 0;
      setInv(await r.json());
    } catch {
      setError("Could not load invoices.");
    }
    setLoad(false);
  }

  const filtered = filter==="ALL" ? invoices : invoices.filter(i=>i.status===filter);

  const stats = {
    total: invoices.length,
    paid:  invoices.filter(i=>i.status==="PAID").length,
    pending: invoices.filter(i=>i.status==="PENDING").length,
    revenue: invoices.filter(i=>i.status==="PAID").reduce((a,i)=>a+i.totalAmount,0),
  };

  return (
    <div style={{display:"flex",flexDirection:"column",gap:20}}>

      {/* stats row */}
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>
        {[["Total Invoices",stats.total,"📋"],["Paid",stats.paid,"✅"],["Pending",stats.pending,"⏳"],["Revenue",fmt(stats.revenue),"💰"]].map(([label,val,icon])=>(
          <div key={label} className="prov-card" style={{padding:"18px 20px",display:"flex",alignItems:"center",gap:12}}>
            <div style={{fontSize:"1.4rem"}}>{icon}</div>
            <div>
              <div style={{fontFamily:"'Outfit',sans-serif",fontWeight:800,fontSize:"1.2rem",color:"var(--g1)",lineHeight:1}}>{val}</div>
              <div style={{fontSize:".68rem",fontWeight:700,textTransform:"uppercase",letterSpacing:".07em",color:"var(--text-s)",marginTop:3}}>{label}</div>
            </div>
          </div>
        ))}
      </div>

      {/* list */}
      <div className="prov-card">
        <div className="prov-header">
          <div className="prov-section-icon">📋</div>
          <div><h2 className="prov-title">Invoice History</h2><p className="prov-sub">All invoices generated by your practice</p></div>
        </div>

        {/* filter tabs */}
        <div style={{display:"flex",gap:8,marginBottom:20}}>
          {["ALL","PAID","PENDING","CANCELLED"].map(s=>(
            <button key={s} onClick={()=>setFilter(s)}
              style={{padding:"6px 16px",borderRadius:8,border:"1px solid var(--border-m)",fontWeight:600,fontSize:".78rem",cursor:"pointer",transition:"all .2s",
                background: filter===s ? "linear-gradient(135deg,var(--g1),var(--teal))" : "#fff",
                color: filter===s ? "#fff" : "var(--text-m)"}}>
              {s}
            </button>
          ))}
        </div>

        {error && <div className="prov-error">{error}</div>}

        {loading ? (
          <div style={{textAlign:"center",padding:"40px",color:"var(--text-s)"}}>
            <div className="prov-spinner" style={{margin:"0 auto 12px"}}/>Loading invoices…
          </div>
        ) : filtered.length === 0 ? (
          <div style={{textAlign:"center",padding:"48px",color:"var(--text-s)",border:"1px dashed var(--border-m)",borderRadius:12}}>
            No invoices found.
          </div>
        ) : (
          <div style={{display:"flex",flexDirection:"column",gap:12}}>
            {filtered.map(inv=>(
              <div key={inv.invoiceId} style={{background:"#f9fefb",border:"1px solid var(--border)",borderRadius:12,padding:"16px 20px",display:"grid",gridTemplateColumns:"1fr 1fr 1fr auto",alignItems:"center",gap:"12px 24px"}}>
                <div>
                  <div style={{fontFamily:"'Outfit',sans-serif",fontWeight:700,color:"var(--text)",fontSize:".95rem"}}>{inv.invoiceNumber}</div>
                  <div style={{fontSize:".72rem",color:"var(--text-s)",marginTop:2}}>Patient ID: #{inv.patientId} · Provider: #{inv.providerId}</div>
                </div>
                <div>
                  <div style={{fontSize:".68rem",fontWeight:700,textTransform:"uppercase",letterSpacing:".06em",color:"var(--text-s)"}}>Invoice Date</div>
                  <div style={{fontSize:".875rem",color:"var(--text)",marginTop:2}}>{inv.invoiceDate}</div>
                </div>
                <div>
                  <div style={{fontSize:".68rem",fontWeight:700,textTransform:"uppercase",letterSpacing:".06em",color:"var(--text-s)"}}>Total</div>
                  <div style={{fontFamily:"'Outfit',sans-serif",fontWeight:800,color:"var(--g1)",fontSize:"1rem",marginTop:2}}>{fmt(inv.totalAmount)}</div>
                </div>
                <span style={{padding:"4px 14px",borderRadius:100,fontWeight:700,fontSize:".72rem",letterSpacing:".05em",...(STATUS_STYLE[inv.status]||STATUS_STYLE.PENDING)}}>
                  {inv.status}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}